
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-set
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
      - name: init-mariadb
        image: busybox
        command: ['sh', '-c', 'mkdir -p /home/mariadb']
        volumeMounts:
        - name: backup-script
          mountPath: /home/mariadb
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-store
          mountPath: /var/lib/mysql
        - name: db-init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
        - name: backup-script
          mountPath: /home/mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-password
                key: password
      volumes:
      - name: db-init-script
        configMap:
          name: db-init-script
  volumeClaimTemplates:
  - metadata:
      name: mariadb-store
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: backup-script
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi


---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mariadb-backup
            image: busybox
            command: ["/bin/bash", "-c", "/home/mariadb/mariadb-backup.sh"]
            volumeMounts:
            - name: backup-script
              mountPath: /home/mariadb
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
          volumes:
          - name: backup-script
            hostPath:
              path: /home/mariadb/mariadb-backup.sh
          restartPolicy: OnFailure


mount info
10.170.70.174:/home/share/nfs  81121280  3622912  77481984   5% /home/share/nfs-master


cronjob 2
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mariadb-backup
            image: busybox
            command: ["/bin/sh", "-c", "/home/mariadb/mariadb-backup.sh"]
            volumeMounts:
            - name: backup-script
              mountPath: /home/mariadb
              readOnly: true
            - name: backup-config
              mountPath: /home/mariadb/mariadb-backup.sh
              subPath: mariadb-backup.sh
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
          volumes:
          - name: backup-script
            configMap:
              name: mariadb-backup-script
          - name: backup-config
            configMap:
              name: mariadb-backup-script
          restartPolicy: OnFailure

apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: create-mariadb-dir
            image: busybox
            command: ["/bin/sh", "-c", "mkdir -p /home/mariadb"]
            volumeMounts:
            - name: backup-script
              mountPath: /home/mariadb
          containers:
          - name: mariadb-backup
            image: mariadb
            command: ["/bin/sh", "-c", "/home/mariadb/mariadb-backup.sh"]
            volumeMounts:
            - name: backup-script
              mountPath: /home/mariadb
              readOnly: true
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
          volumes:
          - name: backup-script
            configMap:
              name: mariadb-backup-script
          restartPolicy: OnFailure


spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
  name: mariadb-backup
spec:
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
    spec:
      template:
        spec:
          initContainers:
          - name: init-mariadb-backup
            imgae: busybox
            command: ['sh', '-c', 'mkdir -p /home/mariadb']
            volumeMounts:
            - name: backup-script
              mountPath: /home/mariadb
          containers:
          - name: mariadb-backup
            image: mariadb
            command: ["/bin/sh", "-c", "/home/mariadb/mariadb-backup.sh"]
            volumeMounts:
            - name: backup-script
              mountPath: /home/mariadb
              readOnly: true
            - name: backup-config
              mountPath: /home/mariadb/mariadb-backup.sh
              subPath: mariadb-backup.sh
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
          volumes:
          - name: backup-script
            configMap:
              name: mariadb-backup-script
          restartPolicy: OnFailure



