apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
spec:
  selector:
    app: mysql-cluster
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
spec:
  selector:
    matchLabels:
      app: mysql-cluster
  serviceName: mysql-cluster
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-cluster
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: percona/percona-xtradb-cluster:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
        command:
        - /bin/bash
        - -c
        - |
          # configure node
          if [ $(hostname -s) = "mysql-cluster-0" ]; then
            mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE USER 'cluster'@'%' IDENTIFIED BY 'cluster'; GRANT ALL PRIVILEGES ON *.* TO 'cluster'@'%' WITH GRANT OPTION;"
            service mysql bootstrap-pxc
          else
            service mysql start
          fi
        - name: mysql-persistent-storage
          mountPath: /mnt/config
        command:
        - "bash"
        - "-c"
        - "cp /etc/mysql/my.cnf /mnt/config/my.cnf && exec /usr/bin/mysqld --defaults-file=/mnt/config/my.cnf"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: password
          - name: XTRABACKUP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xtrabackup-password
                key: password
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: mysql-config
        configMap:
          name: my-cnf
          items:
            - key: my.cnf
              path: my.cnf
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "bami-sc"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "bami-sc"
      resources:
        requests:
          storage: 1Gi






---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
spec:
  selector:
    matchLabels:
      app: mysql-cluster
  serviceName: mysql-cluster
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-cluster
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: percona/percona-xtradb-cluster:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
        command:
        - /bin/bash
        - -c
        - |
          # configure node
          if [ $(hostname -s) = "mysql-cluster-0" ]; then
            mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE USER 'cluster'@'%' IDENTIFIED BY 'cluster'; GRANT ALL PRIVILEGES ON *.* TO 'cluster'@'%' WITH GRANT OPTION;"
            service mysql bootstrap-pxc
          else
            service mysql start
          fi
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: password
          - name: XTRABACKUP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xtrabackup-password
                key: password
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "mkdir -p /mnt/config && chown 1001:1001 /mnt/config &&  cp /etc/mysql/my.cnf /mnt/config/my.cnf && exec /usr/bin/mysqld --defaults-file=/mnt/config/my.cnf"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /mnt/config
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: mysql-config
        configMap:
          name: my-cnf
          items:
            - key: my.cnf
              path: my.cnf
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
        emptyDir: {}  
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "bami-sc"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "bami-sc"
      resources:
        requests:
          storage: 1Gi



apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cnf
data:
  my.cnf: |-
    [mysqld]
    datadir=/var/lib/mysql
    user=mysql
    
    # Path to Galera library
    wsrep_provider=/usr/lib/libgalera_smm.so
    
    # Cluster connection URL contains the IPs of node#1, node#2 and node#3
    wsrep_cluster_address=gcomm://10.170.70.201,10.170.70.246
    
    # In order for Galera to work correctly binlog format should be ROW
    binlog_format=ROW
    
    # Using the MyISAM storage engine is not recommended
    default_storage_engine=InnoDB
    
    # This InnoDB autoincrement locking mode is a requirement for Galera
    innodb_autoinc_lock_mode=2
    
    # Node #1 address
    wsrep_node_address=10.170.70.201
    
    # SST method
    wsrep_sst_method=xtrabackup-v2
    
    # Cluster name
    wsrep_cluster_name=bami_mysql_cluster
    
    # Authentication for SST method                                                          
    wsrep_sst_auth="admin:admin"                
---
