apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
  - name: nfs-pvc
    persistentVolumeClaim:
      claimName: mariadb-pvc
  containers:
    - name: nfs-pvc-test
      image: nginx:alpine
      ports:
      - containerPort: 80

      volumeMounts:
        - name: nfs-pvc
          mountPath: /tmp
