apiVersion:  v1
kind: ConfigMap
metadata:
  name: mysql-msa-user-config
data:
  init.sql: |
		CREATE DATABASE msa_user default CHARACTER SET UTF8;
		USE msa_user;
		CREATE TABLE `TB_USER` (
		  `user_seq` int(11) NOT NULL AUTO_INCREMENT,
		  `user_id` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
		  `user_passwd` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
		  `user_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
		  `use_yn` varchar(1) COLLATE utf8_unicode_ci DEFAULT 'Y',
		  `create_dt` datetime NOT NULL,
		  `update_dt` datetime NOT NULL,
		  PRIMARY KEY (`user_seq`),
		  UNIQUE KEY `id_key` (`user_id`)
		) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-msa-user
spec:
  selector:
    matchLabels:
      app: mysql-user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-user
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql-user
        volumeMounts:
        - name: mysql-msa-user-config
          mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
      - name: mysql-user
      - name: mysql-msa-user.config
        configMap:
          name: mysql-msa-user-config
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-msa-user
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30401
  selector:
    app: mysql-user
