apiVersion:  v1
kind: ConfigMap
metadata:
  name: mysql-msa-board-config
data:
  init.sql: |
    CREATE DATABASE msa_board default CHARACTER SET UTF8;
    USE msa_board;
		CREATE TABLE `TB_BOARD` (
		  `board_seq` int(11) NOT NULL AUTO_INCREMENT,
		  `board_title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
		  `board_text` mediumtext COLLATE utf8_unicode_ci,
		  `write_user_id` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
		  `write_user_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
		  `use_yn` varchar(1) COLLATE utf8_unicode_ci DEFAULT 'Y',
		  `create_dt` datetime NOT NULL,
		  `update_dt` datetime NOT NULL,
		  PRIMARY KEY (`board_seq`)
		) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-msa-board
spec:
  selector:
    matchLabels:
      app: mysql-board
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-board
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-board
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql-board
        volumeMounts:
        - name: mysql-msa-board-config
          mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
      - name: mysql-board
      - name: mysql-msa-board.config
        configMap:
          name: mysql-msa-board-config


---
apiVersion: v1
kind: Service
metadata:
  name: mysql-msa-board
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30501
  selector:
    app: mysql-board
