def projects = [
  'edu-msa-board-master',
  'edu-msa-comment-master',
  'edu-msa-ui-master',
  'edu-msa-user-master'
]

pipeline {
  agent any

  tools {
    maven 'maven'
  }


  stages {
    stage('Checkout Projects') {
      steps {
        git url: 'https://github.com/seunghyejeong/gitops-repository.git', branch: 'main'
      }
    }

    stage('SonarQube Analysis') {
      steps {
        script {
         withCredentials([
          string(credentialsId: 'jenkins-sonarqube', variable: 'SONAR_TOKEN')
         ]) {
          for (def project in projects) {
            dir(project) {
              withSonarQubeEnv('sonarqube') {
                sh 'mvn clean package sonar:sonar'
              }
            }
          }
        }
      }
    }
  }
}
}
