apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "0 17 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mariadb-backup
            image: mariadb
            command: ["/bin/sh", "-c", "mysqldump -u admin -padmin -h 10.233.120.181 --port 3306 test > /mnt/$(date '+%Y-%m-%d').sql"]
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-password
                  key: password
            volumeMounts:
            - name: backup-script
              mountPath: /mnt
          volumes:
           - name: backup-script
             persistentVolumeClaim:
               claimName: backup-script-mariadb-set-0
          restartPolicy: OnFailure
