apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-zuul
  labels:
    app: zuul-msa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-msa
  template:
    metadata:
      labels:
        app: zuul-msa
    spec:
      containers:
      - name: zuul-msa
        image: seunghyejeong/edu-msa-zuul-master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 28081      
        env:             
        - name: BOARD_MSA_URL
          value: "edu-msa-board.msa.svc.cluster.local:28082"
        - name: COMMENT_MSA_URL
          value: "edu-msa-comment.msa.svc.cluster.local:28083"
        - name: USER_MSA_URL
          value: "edu-msa-user.msa.svc.cluster.local:28084"          
      imagePullSecrets:
         - name: edu-msa-secret       
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-zuul
  labels:
    app: zuul-msa  
spec:
  ports:
  - nodePort: 30801
    port: 28081
    protocol: TCP
    targetPort: 28081
  selector:
    app: zuul-msa
  type: NodePort
