apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-comment
  labels:
    app: comment-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-msa
  template:
    metadata:
      labels:
        app: comment-msa
    spec:
      containers:
      - name: comment-msa
        image:  seunghyejeong/edu-msa-comment-master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 28083    
      imagePullSecrets:
         - name: edu-msa-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-comment
  labels:
    app: comment-msa  
spec:
  ports:
  - nodePort: 30301
    port: 28083
    protocol: TCP
    targetPort: 28083
  selector:
    app: comment-msa
  type: NodePort
