apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-board
  labels:
    app: board-msa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-msa
  template:
    metadata:
      labels:
        app: board-msa
    spec:
      containers:
      - name: board-msa
        image: seunghyejeong/edu-msa-board-master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 28082         
      imagePullSecrets:
         - name: edu-msa-secret        
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-board
  labels:
    app: board-msa  
spec:
  ports:
  - nodePort: 30501
    port: 28082
    protocol: TCP
    targetPort: 28082
  selector:
    app: board-msa
  type: NodePort

